wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.5
    framework: huggingface
    huggingface_version: 4.24.0
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.7.15
    start_time: 1669814306.617672
    t:
      1:
      - 1
      - 5
      - 11
      - 49
      - 51
      - 53
      - 55
      2:
      - 1
      - 5
      - 11
      - 49
      - 51
      - 53
      - 55
      3:
      - 16
      - 23
      4: 3.7.15
      5: 0.13.5
      6: 4.24.0
      8:
      - 5
architecture:
  desc: null
  value: BERT
dataset_id:
  desc: null
  value: HW4-P3-MLP-546
learning_rate:
  desc: null
  value: 0.0002
